### ISSUE TITLE
Doesnt work. 

### ISSUE THREAD

**Issue by RylanYancey** [Lapz/perlin_noise#1]
This just outputs the exact same variable for every input. 

```rs
extern crate perlin_noise as perlin;
use  perlin::PerlinNoise;

const WIDTH:i32 = 100;
const HEIGHT:i32 = 100;

fn main() {
    let perlin = PerlinNoise::new();

    //let mut v: f64 = 0.0;
    for x in 0..WIDTH {
        print!("\n");
        for y in 0..HEIGHT {
            print!(" {}", perlin.get2d([x as f64, y as f64]));
        }
    }
}
```

Outputs: 

![image](https://user-images.githubusercontent.com/76256852/147297564-5f3d1bf6-3dac-4849-a0d6-1c20cbe3a153.png)

nothing but 0.46875 over and over and over again

its a shame

**Comment by RylanYancey** [comment]
Looking back; was kinda stupid; closing;

**Comment by mrspeaker** [comment]
> Looking back; was kinda stupid; closing;

What was the answer?! Nothing in the code base says what the limits of the inputs are - I'm getting lots of 0.46875 unless I scale my inputs (divide them down) but I can't figure out what the acceptable range is.

**Comment by RylanYancey** [comment]
> > Looking back; was kinda stupid; closing;
> 
> What was the answer?! Nothing in the code base says what the limits of the inputs are - I'm getting lots of 0.46875 unless I scale my inputs (divide them down) but I can't figure out what the acceptable range is.

You have to scale your inputs down, according to the paper `Simplex Noise Demystified`, whole number points are always zero (or some constant depending on the implementation). Try dividing by a small number like 0.001.

**Comment by mrspeaker** [comment]
Thanks! Seems like the inputs need to be less than 1.0 otherwise you just get back the dreaded 0.46875... which is weird because the README examples are whole numbers greater than 1.0.
